fix: authz exec and coverage directory location
strangelove-ventures/interchaintest pull request #1173
Opened 2024-07-05 15:35 UTC by fmorency

This PR

- Passes environment variable context when creating the AuthZ JSON file containing the nested message to be executed
- Fixed the coverage directory to match `HomeDir()`

@Reecepbcups

2024-07-05 22:52 UTC, Reecepbcups approved these changes
LGTM

2024-07-08 13:36 UTC, fmorency commented
The failing test in the previous run is unrelated to this PR. It also fails on the `v8.5.0` tag.

2024-07-15 10:32 UTC, Reecepbcups commented
Failing e2e test is related:

```
    code_coverage_test.go:87: 
        	Error Trace:	/home/runner/work/interchaintest/interchaintest/examples/cosmos/code_coverage_test.go:87
        	            				/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1175
        	            				/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1353
        	            				/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1683
        	Error:      	Should NOT be empty, but was []
        	Test:       	TestCodeCoverage
```

Code coverage is not finding coverage files in the home dir. It was originally pulling `/var/cosmos-chain/manifest-2` which is where it is actually stored (not name), but due to that being the core repo it is possible the output never actually happened for the cov files
![image](https://github.com/user-attachments/assets/60a0046c-7f1d-4efa-ae2d-85097921b258)

2024-07-15 10:33 UTC, Reecepbcups requested changes
Failing e2e test is related:

```
    code_coverage_test.go:87: 
        	Error Trace:	/home/runner/work/interchaintest/interchaintest/examples/cosmos/code_coverage_test.go:87
        	            				/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1175
        	            				/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1353
        	            				/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1683
        	Error:      	Should NOT be empty, but was []
        	Test:       	TestCodeCoverage
```

Code coverage is not finding coverage files in the home dir. It was originally pulling `/var/cosmos-chain/manifest-2` which is where it is actually stored (not name), but due to that being the core repo it is possible the output never actually happened for the cov files
![image](https://github.com/user-attachments/assets/60a0046c-7f1d-4efa-ae2d-85097921b258)

2024-07-15 16:00 UTC, Reecepbcups commented on examples/cosmos/code_coverage_test.go
> -			ChainName:     cfgA.ChainID,
ahhhh

2024-07-15 16:00 UTC, Reecepbcups approved these changes

2024-07-15 16:34 UTC, merged